Core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("register/", views.signup, name="signup"),
    path("login/", views.login_user, name="login"),
    # password reset urls
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password-reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    # # activate account
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
]

access_key_manager/urls.py
from django.contrib import admin
from django.urls import path, include


admin.site.site_title = "Micro Focus Inc"
admin.site.site_header = "Micro Focus Inc."
admin.site.index_title = "Key Manager Administration"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("key_manager.urls", namespace="key_manager")),
    path("accounts/", include("Core.urls")),
]

key_manager/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from . import views

app_name = "key_manager"

urlpatterns = [
    path("", views.MangeKeysListView.as_view(), name="dashboard"),
    path("create/", views.CreateNewKey.as_view(), name="create_key"),
    # endpoints
    path(
        "api/check_key_status/<str:email>/",
        views.CheckKeyStatus.as_view(),
        name="check_key_status",
    ),
    path(
        "api/token/",
        views.MicroFocusTokenObtainPairView.as_view(),
        name="token_obtain_pair",
    ),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refesh"),
]

key_manager/models.py
from datetime import timedelta
from django.db import models
from django.utils import timezone
from django.conf import settings

import uuid


class ActiveKeyManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super().get_queryset().filter(status=AccessKey.Status.ACTIVE)


# Create your models here.
class AccessKey(models.Model):
    """
    Table to manage Keys
    """

    class Status(models.TextChoices):

        ACTIVE = "active", "Active"
        EXPIRED = "expired", "Expired"
        REVOKED = "revoked", "Revoked"

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="keys")
    key = models.UUIDField(default=uuid.uuid4, editable=False)
    status = models.CharField(max_length=7, choices=Status.choices)
    procurement_date = models.DateTimeField(default=None)
    expiry_date = models.DateTimeField(default=None)
    updated_on = models.DateTimeField(auto_now=True)

    objects = models.Manager()  # The default manager
    activeKeys = ActiveKeyManager()  # Returns the active key

    class Meta:
        ordering = ["-procurement_date"]
        indexes = [
            models.Index(
                fields=[
                    "status",
                    "procurement_date",
                ]
            ),
        ]
        verbose_name_plural = "Access Key"

    def __str__(self):
        return self.status

    def save(self, *args, **kwargs):
        if self.expiry_date is None:
            self.expiry_date = timezone.now() + timedelta(days=30)

        if self.procurement_date is None:
            self.procurement_date = timezone.now()

        super(AccessKey, self).save(*args, **kwargs)

key_manager/views.py
import re
from django.views import generic, View
from django.shortcuts import redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.utils import timezone

from rest_framework.views import APIView
from rest_framework import status
from rest_framework.response import Response
from rest_framework import authentication
from rest_framework_simplejwt.authentication import JWTAuthentication


from .models import AccessKey
from .serializers import AccessKeySerializer
from .permissions import MicroFocusAdminAPIPermission

from rest_framework_simplejwt.views import TokenObtainPairView

from .serializers import MicroFocusObtainPairSerializer


# Create your views here.


class MicroFocusTokenObtainPairView(TokenObtainPairView):
    """Provide token to users"""

    serializer_class = MicroFocusObtainPairSerializer


class OwnerMixin:
    """
    filtered based on the user
    """

    def get_queryset(self):
        # check the status of the latest key provided
        latest_key = super().get_queryset().filter(user=self.request.user).first()

        # check if the latest key exists and if it has expired
        if latest_key and latest_key.expiry_date < timezone.now():
            # update the status to expired
            latest_key.status = AccessKey.Status.EXPIRED
            latest_key.save()

        # Retrieve all keys for the user
        qs = super().get_queryset().filter(user=self.request.user)

        return qs


class MangeKeysListView(OwnerMixin, LoginRequiredMixin, generic.ListView):
    """
    List keys related to the requested user
    """

    paginate_by = 3
    model = AccessKey
    context_object_name = "keys"
    template_name = "key_manager/dashboard.html"


# List of drecorators to decorate the CreateNewKey class
decorators = [require_POST, login_required]


@method_decorator(decorators, name="dispatch")
class CreateNewKey(View):

    def post(self, request, *args, **kwargs):
        user = request.user
        key_obj = AccessKey.objects.filter(
            status=AccessKey.Status.ACTIVE, user=request.user
        ).exists()
        if not key_obj:
            AccessKey.objects.create(user=user, status=AccessKey.Status.ACTIVE)
            messages.success(request, "New key was created successfully")
            return redirect("key_manager:dashboard")

        messages.error(request, "There is already an active key")
        return redirect("key_manager:dashboard")


class CheckKeyStatus(APIView):
    """
    View to check and return key based on the status.
    """

    authentication_classes = [
        authentication.SessionAuthentication,
        JWTAuthentication,
    ]
    permission_classes = [MicroFocusAdminAPIPermission]

    def get(self, request, email, format=None):
        user_model = get_user_model()
        email_pattern = r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"
        if re.match(email_pattern, email):
            try:
                user = user_model.objects.get(email=email)
                active_key = AccessKey.activeKeys.filter(user=user).first()
                if active_key:
                    if active_key.expiry_date >= timezone.now():
                        serializer = AccessKeySerializer(active_key)
                        return Response(serializer.data, status=status.HTTP_200_OK)
                    else:
                        # update the status to expired
                        active_key.status = AccessKey.Status.EXPIRED
                        active_key.save()
                return Response(
                    {"error": "No active Key found"},
                    status=status.HTTP_404_NOT_FOUND,
                )

            except user_model.DoesNotExist:
                return Response(
                    {"error": "User not found"}, status=status.HTTP_404_NOT_FOUND
                )
        return Response(
            {"error": "invalid email proivided"}, status=status.HTTP_400_BAD_REQUEST
        )

key_manager/templates/key_manager/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dashboard</title>
    {% comment %} <link rel="stylesheet" href="style.css" /> {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}" />
  </head>

  <body>
    <header>
      <div class="logo">
        <a href="#">Access Key Manager</a>
      </div>
      <nav>
        <ul class="nav-items">
          <li class="username">{{ request.user.email }}</li>
          <li>
            <form action="{% url 'logout' %}" method="post">
              {% csrf_token %}
              <input type="submit" value="Logout" class="logout" />
            </form>
          </li>
        </ul>
      </nav>
      <div class="request-new-key">
         <form action="{%  url 'key_manager:create_key' %}" method="post">
              {% csrf_token %}
              <input class="request-key" type="submit" value="Request a Key">
            </form>
      </div>
    </header>

    <main>
      <section>
        <div class="keys-container">
          {% if messages %}
            {% for message in messages %}
              <div class="alert {{message.tags }}">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                {{ message }}
              </div>
             
            {% endfor %}
          {% endif %}
          {% for key in keys %}
          <div class="key-item {{ key.status }}">
            <div class="status-container flex-layout">
              <div class="key-label">Status:</div>
              <div class="{{ key.status }}-txt-color">{{ key.status }}</div>
            </div>

            <div class="key-con flex-layout">
              <div class="key-label">Key:</div>
              <div>{{ key.key }}</div>
            </div>

            <div class="pro-date flex-layout">
              <div class="key-label">Pro. Date:</div>
              <div>{{ key.procurement_date }}</div>
            </div>

            <div class="exp-date flex-layout">
              <div class="key-label">Exp. Date:</div>
              <div> {{ key.expiry_date }}</div>
            </div>
          </div>
          {% empty %}

          <div class="no-keys-container">
            <p class="no-keys-msg">You have No Keys Yet. Request a Key</p>
            <form action="{%  url 'key_manager:create_key' %}" method="post">
              {% csrf_token %}
              <input class="request-key" type="submit" value="Request a Key">
            </form>
          </div>

          {% endfor %}

      </section>

      <!-- pagination -->
      <section>
        <div class="pagination-section">
          {% if is_paginated %}
          <p>{{ page_obj.current_page_number }}</p>
            {% if page_obj.has_previous %}
              <a class="page-btn" href="?page={{ page_obj.previous_page_number }}">&laquo; PREV</a>
            {% endif %}
            
              {% if page_obj.has_next %}
                <a class="page-btn" href="?page={{ page_obj.next_page_number }}">NEXT &raquo;</a>
              {% endif %}    
          {% endif %}      
        </div>
      </section>
    </main>
  </body>
</html>